export const userTest = {
  telefonoEmpresa: '0978892495',
  email_contacto: 'santiago.moreno52@gmail.com',
  email: 'admin@rapifas.com',
  direccion: 'Pradera, Arupos y nogales',
  rol: 'admin',
  referencia: 'Casa esquinera',
  ruc: '1102144811',
  telefonoResponsable: '0978892495',
  nombres: 'administrador',
  apellidos: 'administrador',
  id: '1YvC3ZTa8OeXN3AiXXTJEGUL2Pl1',
  fuctions: {
    ventas_crear: true,
    factura_crear: true,
    factura_buscar: true,
    balances_crear: true,
    balances_buscar: true,
    inventario_crear: true,
    usuarios_crear: true,
    usuarios_acciones: true,
  },
}
